### ISSUE TITLE
Delay in Start the Streaming of Screen Share

### ISSUE THREAD

**Issue by yadavendra15** [AirenSoft/OvenLiveKit-Web#1]
Hi Oven Team,

When I tried start the Screen Share streaming, it takes some time to start the streaming. 
I didn't find the reason of the delay in the start.

Hoping for fixed this issue soon.

**Comment by SangwonOh** [comment]
Screen capture is now stable. Closing this issue. (refer https://github.com/AirenSoft/OvenLiveKit-Web/issues/10)
