### ISSUE TITLE
Need to access audio streaming DOM to build a mute button

### ISSUE THREAD

**Issue by dprisikar** [AirenSoft/OvenLiveKit-Web#11]
Hi,

I am working on adding a mute/unmute button to the kit that streams audio (no video). 

I am trying to access with DOM the incoming stream from a user's microphone, but can't really accomplish this.

Here is a code snippet:

```
<script>
// Initialize OvenLiveKit
let ovenLivekit = OvenLiveKit.create();
// Get media stream from user device
ovenLivekit.getUserMedia({video: false, audio: true}).then(function () {
    // Got device stream and start streaming to OvenMediaEngine
    ovenLivekit.startStreaming('wss://your_oven_media_engine:3333/app/stream?direction=send');
});

document.getElementById("muteBtn").onclick = function(evt) {
const newState = !ovenLivekit.getAudioTracks[0].enabled;
document.getElementById("muteBtn").innerHTML = newState ? "&#x25B6;&#xFE0F;" : "&#x23F8;&#xFE0F;";
ovenLivekit.getAudioTracks[0].enabled = newState;
 }
</script>

```
=======
I am trying to access the microphone stream with ovenLivekit.getAudioTracks[0], but it does not work. Returns "Uncaught TypeError: Cannot read properties of undefined (reading '0')"

Any help with this is very much appreciated!

**Comment by IanMitchell77** [comment]
I guess that its not streaming at the point you call getAudioTracks so you need to check that it returns something before calling the enable function.

**Comment by dprisikar** [comment]
@IanMitchell77 , thanks again for helping me out!

As soon as the page loads, the microphone is accessed, and a little red dot indicator at the top of the page, where the page tab is, appears. 

Plus, the console returns "OvenLiveKit.js : Received Media Stream From Input Device", with MediaStream {id, ...} 

To my understanding, this means that the audio is streaming. 

Here is the page code for reference; this is the latest version, as is (I have tried accessing the audio stream with MediaStream.getAudioTracks[0], but the result is the same):

```
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
    <link rel="stylesheet" href="style.css">
    
</head>

<body class="text-center body-centered">

  <main class="form-centered">
    <form>
      <div class="form-floating mb-4">
        <input type="button" class="button-publish" id="muteBtn" value="GO LIVE">
      </div>
       </form>  
  </main>

<!-- Voice capture script -->
<script src="https://cdn.jsdelivr.net/npm/ovenlivekit@latest/dist/OvenLiveKit.min.js"></script><script defer="defer" src="fda0b8224f3acb87a87b.bundle.js"></script>
   
<script>
// Initialize OvenLiveKit
let ovenLivekit = OvenLiveKit.create();
// Get media stream from user device
ovenLivekit.getUserMedia({video: false, audio: true}).then(function () {
    // Got device stream and start streaming to OvenMediaEngine
    ovenLivekit.startStreaming('wss://your_oven_media_engine:3333/app/stream?direction=send');
});

document.getElementById("muteBtn").onclick = function(evt) {
const newState = !MediaStream.getAudioTracks[0].enabled;
document.getElementById("muteBtn").innerHTML = newState ? "&#x25B6;&#xFE0F;" : "&#x23F8;&#xFE0F;";
MediaStream.getAudioTracks[0].enabled = newState;
 }
</script>

<!-- Bootstrap script -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  

</body></html>
```

**Comment by IanMitchell77** [comment]
hang on! MediaStream isnt anything - maybe it should be ovenLivekit?

**Comment by IanMitchell77** [comment]
Try printing the contents of MediaStream, and MediaStream.getAudioTracks[0]

**Comment by dprisikar** [comment]
Running console.log(ovenLiveKit.stream); 

This returns MediaStream {...}, but when trying to access getAudioTracks, the console logging returns "undefined".

**Comment by dprisikar** [comment]
Thank you, @IanMitchell77 for your input, definitely, appreciate it!

**Comment by dprisikar** [comment]
Still, no luck on my end. 

Perhaps, @dimiden, @getroot, @SangwonOh would find a minute to spare to help me out with this?

**Comment by dprisikar** [comment]
![Inkedphoto_2022-07-11_19-32-43](https://user-images.githubusercontent.com/101226750/178324117-9fde3861-5fca-47f7-a223-908cdb45fa4a.jpg)

**Comment by dprisikar** [comment]
My latest try has been doing this with

ovenLivekit.MediaStreamTrack.enabled

But, it's not working.

**Comment by SangwonOh** [comment]
@dprisikar Hi. Is your problem solved?

**Comment by dprisikar** [comment]
@SangwonOh, thank you for checking up on me. Yes, I have managed to find a solution.

**Comment by owengiri20** [comment]
> @SangwonOh, thank you for checking up on me. Yes, I have managed to find a solution.

Hi, what was your solution? (I'm having a similar issue)
