### ISSUE TITLE
Problem with getDevices function

### ISSUE THREAD

**Issue by yginuo** [AirenSoft/OvenLiveKit-Web#3]
hello 

If width and height are set when retrieving audio and video sources. In some cases, the browser has a "NotFoundError" error, but sometimes it's fine, and I think it's a browser problem. However, I still recommend not setting width and height, or setting a smaller resolution

![image](https://user-images.githubusercontent.com/18584367/146867312-42fc8534-d60f-47fd-813c-e36d83fd8127.png)

**Comment by SangwonOh** [comment]
@yginuo Hi. I've seen that sometimes a NotFoundError error occurs when the browser can't handle it. 

As you said, it's probably better not to set the resolution by default. But I think it should be possible to make that configuration changeable when initializing OvenLiveKit. I will make some update.

**Comment by SangwonOh** [comment]
@yginuo This issue fixed at f4c925b33921f727ec9bd7817a55f2d6dacf5d44. Thanks again.
