### ISSUE TITLE
Can push screen to OME like getDisplayMedia() using OvenLiveKit?

### ISSUE THREAD

**Issue by buithevuong** [AirenSoft/OvenLiveKit-Web#8]
As title, can I push media stream from my desktop to OME?

**Comment by SangwonOh** [comment]
@buithevuong Hi. There is a display capture feature we haven't revealed yet.

https://github.com/AirenSoft/OvenLiveKit-Web/blob/17e7387782bc63485ea6694cda18a2b2d7161ab9/src/OvenLiveKit.js#L222

Usage is the same as getUserMedia...

```javascript
ovenLivekit.getDisplayMedia().then(function () {

    const connectionConfig = {
        iceServers : null ,
        iceTransportPolicy: null,
        maxBitrate: null
    }

    // Got media stream from user device and start to stream to OvenMedieEngeine
    ovenLivekit.startStreaming(connectionUrl, connectionConfig);
});
```
However, there is an issue with the display capture, so we have not released it yet.
> Delay in Start the Streaming of Screen Share https://github.com/AirenSoft/OvenLiveKit-Web/issues/1

See also this issue. Maybe this issue can help.
> WebRTC input x-google-start-bitrate hack? https://github.com/AirenSoft/OvenPlayer/issues/202

**Comment by brootle** [comment]
> As title, can I push media stream from my desktop to OME?

hi, did you make it work? I managed to share browser tab, but still problem with sharing entire screen and app window

**Comment by SangwonOh** [comment]
Close this issue due to duplicated. (refer https://github.com/AirenSoft/OvenLiveKit-Web/issues/10)
